from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
import os

def generate_audit_pdf(data: dict, filename: str):
    """
    Generates a professional B2B Product Health Audit Certificate.
    """
    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph("<b>EATLYTIC INDUSTRIAL AUDIT REPORT</b>", styles['Title']))
    story.append(Spacer(1, 12))

    # Product Info
    story.append(Paragraph(f"<b>Product:</b> {data.get('product_name', 'Unknown')}", styles['Normal']))
    story.append(Paragraph(f"<b>Brand:</b> {data.get('brand', 'Unknown')}", styles['Normal']))
    story.append(Paragraph(f"<b>Audit Date:</b> {os.popen('date /t').read().strip()}", styles['Normal']))
    story.append(Spacer(1, 12))

    # Safety Verdict
    verdict = data.get('safety_tier', 'Review Required').upper()
    v_color = colors.green if verdict == 'SAFE' else colors.orange if verdict == 'LIMIT' else colors.red
    story.append(Paragraph(f"<b>Safety Verdict: <font color='{v_color}'>{verdict}</font></b>", styles['Heading2']))
    story.append(Spacer(1, 12))

    # Atwater Physics Check
    story.append(Paragraph("<b>Physics Validation (Atwater-Atkins Check)</b>", styles['Heading3']))
    atwater_status = "PASS" if data.get('atwater_valid') else "FAIL"
    story.append(Paragraph(f"The calculated calorie sum from macros matches the reported energy: <b>{atwater_status}</b>", styles['Normal']))
    story.append(Spacer(1, 12))

    # Red Flags
    if data.get('red_flags'):
        story.append(Paragraph("<b>Critical Red Flags Detected:</b>", styles['Heading3']))
        for flag in data['red_flags']:
            story.append(Paragraph(f"• {flag}", styles['Normal']))
        story.append(Spacer(1, 12))

    # Disclaimer
    story.append(Spacer(1, 24))
    story.append(Paragraph("<font size='8'>This report is generated by the Eatlytic AI Engine v3.0. It is intended for industrial self-audit purposes only.</font>", styles['Italic']))

    doc.build(story)
    return filename
